services:
  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ordenes_transporte
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: servicio_ordenes
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/ordenes_transporte
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["java", "-jar", "target/ServicioOrdenesTransporte-0.0.1-SNAPSHOT.jar"]

volumes:
  mariadb_data:
